CREATE TABLE IF NOT EXISTS public.citizens
(
    id          int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    provider_id int8 NULL,
    CONSTRAINT citizens_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.meters
(
    id          int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    provider_id int8 NULL,
    CONSTRAINT meters_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.readings
(
    consumption  int8                                                                                                                     NOT NULL,
    entity_id    int8                                                                                                                     NOT NULL,
    generated_at timestamp(6)                                                                                                             NOT NULL,
    id           int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    entity_type  varchar(255)                                                                                                             NOT NULL,
    CONSTRAINT readings_pkey PRIMARY KEY (id)
);