CREATE TABLE IF NOT EXISTS public.aggregated_consumptions
(
    average_consumption      int8                                                                                                                     NOT NULL,
    consumption_period_end   timestamp(6)                                                                                                             NOT NULL,
    consumption_period_start timestamp(6)                                                                                                             NOT NULL,
    id                       int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    provider_id              int8                                                                                                                     NOT NULL,
    total_consumption        int8                                                                                                                     NOT NULL,
    CONSTRAINT aggregated_consumptions_pkey PRIMARY KEY (id)
);