allowed_origins: '*'
server:
  port: 8080
spring:
  application:
    name: master_gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: newcastle-service
            uri: https://exciting-calf-tidy.ngrok-free.app
            predicates:
              - Path=/city/newcastle/**
            filters:
              - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
              - stripPrefix=2
          - id: backend-sunderland
            uri: https://backend.qrtechnologys.com
            predicates:
              - Path=/city/sunderland/**
            filters:
              - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
              - stripPrefix=2