allowed_origins: '*'
server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name: master_gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: newcastle-service
            uri: ${gateway.uris.newcastle-service}
            predicates:
              - Path=/city/newcastle/**
            filters:
              - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
              - stripPrefix=2
          - id: backend-sunderland
            uri: ${gateway.uris.sunderland-service}
            predicates:
              - Path=/city/sunderland/**
            filters:
              - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
              - stripPrefix=2
          - id: backend-darlington
            uri: ${gateway.uris.darlington-service}
            predicates:
              - Path=/city/darlington/**
            filters:
              - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
              - stripPrefix=2
