gateway:
  uris:
    newcastle-service: https://exciting-calf-tidy.ngrok-free.app
    sunderland-service: https://backend.qrtechnologys.com
    darlington-service: https://primarily-light-condor.ngrok-free.app
